@TM:1368738924
@N:  :"":0:0:0:-1|Running in 64-bit mode
@N:  :"":0:0:0:-1|Running in 64-bit mode
@N:  :"":0:0:0:-1|Running in 64-bit mode
@W:  :"":0:0:0:-1|Multiple cells (name:cycloneiii_crcblock) exist across languages, picking work.cycloneiii_crcblock, ignoring work.cycloneiii_crcblock@I::"C:\Synopsys\fpga_F201109SP1\lib\altera\altera.v"
@N:  :"":0:0:0:-1|Running in 64-bit mode
@TM:1368738927
@W: BN105 :"":0:0:0:-1|Cannot apply constraint altera_chip_pin_lc to ~ALTERA_ASDO_DATA1~ / RESERVED_INPUT
@W: BN105 :"":0:0:0:-1|Cannot apply constraint altera_chip_pin_lc to ~ALTERA_FLASH_nCE_nCSO~ / RESERVED_INPUT
@W: BN105 :"":0:0:0:-1|Cannot apply constraint altera_chip_pin_lc to ~ALTERA_DATA0~ / RESERVED_INPUT
@W: BN105 :"":0:0:0:-1|Cannot apply constraint altera_chip_pin_lc to ~ALTERA_DCLK~ / RESERVED_INPUT
@W: BN105 :"":0:0:0:-1|Cannot apply constraint altera_chip_pin_lc to ~ALTERA_nCEO~ / RESERVED_OUTPUT_OPEN_DRAIN
@N: BN225 :"":0:0:0:-1|Writing default property annotation file D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\rev_1\ladder_fpga.sap.
@TM:1368738943
@N: BW103 :"":0:0:0:-1|Synopsys Constraint File time units using default value of 1ns 
@N: BW107 :"":0:0:0:-1|Synopsys Constraint File capacitance units using default value of 1pF 
@N: FA174 :"":0:0:0:-1|The following device usage report estimates place and route data. Please look at the place and route report for final resource usage.
@W: FA279 :"":0:0:0:-1|Inconsistent Quartus device library version: Verilog/VHDL was compiled using quartus_II101 device library, but clearbox version is quartus_II121.
@W: FA279 :"":0:0:0:-1|Inconsistent Quartus device library version: Verilog/VHDL was compiled using quartus_II101 device library, but clearbox version is quartus_II121.
@W: FA395 :"":0:0:0:-1|Internal tristates present in the result, most likely due to compile points in design. Quartus may convert them to AND gates.
@TM:1368738927
@W: FA401 :"":0:0:0:-1|This design contains flop with asynchronous set.Altera Hardware doesn't have a flop with asynchronous set.Extracted the set signal from the flop, and implemented the set functionality by creating a latch.
@TM:1368738943
@N: MF249 :"":0:0:0:-1|Running in 64-bit mode.
@N: MF249 :"":0:0:0:-1|Running in 64-bit mode.
@N: MF257 :"":0:0:0:-1|Gated clock conversion enabled 
@N: MF257 :"":0:0:0:-1|Gated clock conversion enabled 
@N: MF321 :"":0:0:0:-1|4 registers to be packed into RAMs/DSPs blocks 
@N: MF333 :"":0:0:0:-1|Generated clock conversion enabled, but no generated clocks found in design 
@N: MF546 :"":0:0:0:-1|Generated clock conversion enabled 
@N: MF546 :"":0:0:0:-1|Generated clock conversion enabled 
@W: MO171 :"":0:0:0:-1|Sequential instance a.2.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.3.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.4.b.c.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.b.c.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.b.c.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.6.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.8.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.14.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.3.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.2.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.4.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.9.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.13.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.11.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.10.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.5.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.12.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.7.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.15.b.c.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.13.d.e.ff2_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.3.d.e.ff2_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.6.d.e.ff2_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.9.d.e.ff2_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.12.d.e.ff2_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.10.d.e.ff2_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.ff2_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.5.d.e.ff2_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.8.d.e.ff2_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.11.d.e.ff2_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.d.e.ff2_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.4.d.e.ff2_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.7.d.e.ff2_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.2.d.e.ff2_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.14.d.e.ff2_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.15.b.c.ff2_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.13.d.e.ff2_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.3.d.e.ff2_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.6.d.e.ff2_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.9.d.e.ff2_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.12.d.e.ff2_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.10.d.e.ff2_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.ff2_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.5.d.e.ff2_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.8.d.e.ff2_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.11.d.e.ff2_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.d.e.ff2_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.4.d.e.ff2_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.7.d.e.ff2_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.2.d.e.ff2_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.14.d.e.ff2_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.15.b.c.ff2_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.16.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.3.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.9.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.18.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.14.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.10.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.5.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.7.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.12.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.11.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.2.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.6.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.13.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.4.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.8.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.15.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.17.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.19.b.c.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.6.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.8.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.14.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.3.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.2.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.4.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.9.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.13.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.11.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.10.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.5.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.12.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.7.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.15.b.c.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.10.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.14.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.18.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.2.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.22.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.12.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.4.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.16.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.20.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.6.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.8.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.13.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.15.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.9.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.3.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.7.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.19.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.17.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.5.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.11.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.21.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.23.b.c.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.10.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.10.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.9.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.9.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.6.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.3.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.11.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.2.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.15.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.29.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.17.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.21.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.20.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.9.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.19.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.27.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.30.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.5.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.22.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.8.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.12.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.3.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.7.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.10.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.6.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.23.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.14.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.31.b.c.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.6.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.3.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.13.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.10.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.19.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.9.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.5.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.20.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.6.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.2.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.4.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.8.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.12.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.15.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.7.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.11.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.17.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.16.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.18.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.14.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.21.b.c.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.6.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.3.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.11.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.2.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.15.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.29.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.17.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.21.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.20.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.9.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.19.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.27.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.30.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.5.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.22.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.8.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.12.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.3.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.7.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.10.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.6.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.23.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.14.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.31.b.c.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.6.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.3.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.13.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.10.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.19.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.9.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.5.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.20.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.6.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.2.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.4.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.8.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.12.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.15.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.7.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.11.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.17.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.16.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.18.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.14.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.21.b.c.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.2.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.3.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.13.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.19.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.5.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.20.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.2.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.4.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.8.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.12.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.15.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.7.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.11.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.17.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.16.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.18.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.14.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.21.b.c.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.6.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.8.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.14.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.3.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.2.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.4.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.9.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.13.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.11.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.10.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.5.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.12.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.7.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.15.b.c.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.2.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.3.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.13.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.19.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.5.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.20.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.2.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.4.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.8.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.12.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.15.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.7.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.11.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.17.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.16.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.18.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.14.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.21.b.c.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.6.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.8.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.14.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.3.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.2.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.4.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.9.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.13.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.11.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.10.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.5.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.12.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.7.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.15.b.c.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.4.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.5.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.7.b.c.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.28.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.24.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.18.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.26.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.25.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.16.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.13.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.4.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.4.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.5.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.7.b.c.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.28.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.24.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.18.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.26.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.25.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.16.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.13.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.4.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.d.e.data_out_2 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.15.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.28.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.29.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.30.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.31.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.4.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.17.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.45.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.46.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.43.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.7.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.41.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.11.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.3.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.16.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.20.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.42.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.24.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.37.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.10.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.23.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.36.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.9.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.22.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.35.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.8.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.14.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.12.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.25.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.38.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.33.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.27.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.0.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.1.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.5.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.18.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.6.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.19.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.32.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.2.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.34.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.21.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.44.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.39.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.40.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.13.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.26.d.e.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance a.47.b.c.data_out_1 reduced to a combinational gate by constant propagation 
@W: MO171 :"":0:0:0:-1|Sequential instance COMP_ladder_fpga_SC_BYPASS_REG.data_out_1 reduced to a combinational gate by constant propagation 
@N: MT204 :"":0:0:0:-1|Auto Constrain mode is disabled because clocks are defined in the SDC file
@N: MT320 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing.
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock.
@W: MT420 :"":0:0:0:-1|Found inferred clock ladder_fpga|testin_echelle with period 1000.00ns. Please declare a user-defined clock on object "p:testin_echelle"
@W: MT420 :"":0:0:0:-1|Found inferred clock ladder_fpga|holdin_echelle with period 1000.00ns. Please declare a user-defined clock on object "p:holdin_echelle"
@TM:1368738927
@W: MT462 :"":0:0:0:-1|Net COMP_LADDER_FPGA_SC_CONFIG.data_in[6] appears to be an unidentified clock source. Assuming default frequency. 
@TM:1368738924
@N: CG364 :"C:\Synopsys\fpga_F201109SP1\lib\altera\quartus_II101\altera_lpm.v":314:7:314:18|Synthesizing module lpm_shiftreg
@N: CG364 :"C:\Synopsys\fpga_F201109SP1\lib\altera\quartus_II101\altera_mf.v":913:7:913:12|Synthesizing module dcfifo
@N: CG364 :"C:\Synopsys\fpga_F201109SP1\lib\altera\quartus_II101\altera_mf.v":2494:7:2494:12|Synthesizing module altpll
@N: CD720 :"C:\Synopsys\fpga_F201109SP1\lib\vhd\std.vhd":123:18:123:21|M
@N: CD720 :"C:\Synopsys\fpga_F201109SP1\lib\vhd\std.vhd":123:18:123:21|M
@N: CG364 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\C__altera_10_0_quartus_eda_fv_lib_verilog\cycloneiii_crcblock.v":14:8:14:26|Synthesizing module cycloneiii_crcblock
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_cell.vhd":26:7:26:13|M
@TM:1368738943
@W: BN132 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_cell.vhd":42:4:42:5|M
@W: BN132 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_cell.vhd":42:4:42:5|M
@W: BN132 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_cell.vhd":42:4:42:5|M
@W: BN132 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_cell.vhd":42:4:42:5|M
@W: BN132 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_cell.vhd":54:4:54:5|M
@W: BN132 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_cell.vhd":54:4:54:5|M
@W: BN132 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_cell.vhd":54:4:54:5|M
@W: BN132 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_cell.vhd":54:4:54:5|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_cell.vhd":62:4:62:5|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_cell.vhd":62:4:62:5|M
@W: MO171 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_cell.vhd":62:4:62:5|M
@W: MO171 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_cell.vhd":62:4:62:5|M
@W: MO171 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_cell.vhd":62:4:62:5|M
@W: MO171 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_cell.vhd":62:4:62:5|M
@W: MO171 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_cell.vhd":62:4:62:5|M
@TM:1368738924
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_cell_avec_pulse.vhd":23:7:23:24|M
@TM:1368738927
@W: MT462 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_cell_avec_pulse.vhd":70:13:70:48|M
@TM:1368738924
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_x_bits.vhd":25:7:25:15|M
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_x_bits.vhd":25:7:25:15|M
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_x_bits.vhd":25:7:25:15|M
@TM:1368738943
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_x_bits.vhd":57:6:57:6|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_x_bits.vhd":57:6:57:6|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_x_bits.vhd":70:6:70:6|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_x_bits.vhd":70:6:70:6|M
@TM:1368738924
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_x_bits_avec_pulse.vhd":25:7:25:26|M
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_x_bits_init.vhd":27:7:27:20|M
@TM:1368738943
@W: BN132 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_x_bits_init.vhd":59:6:59:6|M
@W: BN132 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_x_bits_init.vhd":59:6:59:6|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_x_bits_init.vhd":59:6:59:6|M
@W: BN132 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_x_bits_init.vhd":72:6:72:6|M
@W: BN132 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_x_bits_init.vhd":72:6:72:6|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_x_bits_init.vhd":72:6:72:6|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\dr_x_bits_init.vhd":72:6:72:6|M
@TM:1368738924
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\filtre_latchup.vhd":42:7:42:20|M
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\gestion_hybrides_v4.vhd":37:7:37:25|M
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ir_5_bits.vhd":27:7:27:15|M
@TM:1368738943
@W: BN132 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ir_5_bits.vhd":54:6:54:6|M
@W: BN132 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ir_5_bits.vhd":65:6:65:6|M
@TM:1368738924
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ir_cell.vhd":24:7:24:13|M
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":136:7:136:17|M
@W: CL159 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":160:1:160:13|M
@W: CL159 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":174:4:174:19|M
@W: CL158 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":175:4:175:16|M
@W: CL158 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":176:4:176:16|M
@W: CL159 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":177:4:177:16|M
@W: CL159 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":179:4:179:17|M
@N: CD231 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":232:30:232:31|M
@N: CD231 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":236:31:236:32|M
@N: CD231 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":240:26:240:27|M
@W: CD638 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":589:7:589:35|M
@W: CD638 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":590:7:590:36|M
@TM:1368738943
@W: MT246 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":670:2:670:25|M
@TM:1368738924
@W: NF120 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":670:2:670:25|M
@TM:1368738927
@W: BN393 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":720:2:720:32|M
@TM:1368738943
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":785:2:785:31|M
@N:  :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1204:2:1204:3|M
@N:  :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1204:2:1204:3|M
@N:  :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1204:2:1204:3|M
@N:  :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1204:2:1204:3|M
@N:  :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1204:2:1204:3|M
@TM:1368738924
@W: CL111 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1204:2:1204:3|M
@W: CL169 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1204:2:1204:3|M
@W: CL190 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1204:2:1204:3|M
@W: CL190 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1204:2:1204:3|M
@N: CL201 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1204:2:1204:3|M
@W: CL260 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1204:2:1204:3|M
@W: CL271 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1204:2:1204:3|M
@W: CD609 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1334:24:1334:41|M
@TM:1368738943
@N:  :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1536:2:1536:3|M
@TM:1368738924
@W: CD604 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1565:6:1565:19|M
@TM:1368738943
@N:  :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1579:2:1579:3|M
@TM:1368738924
@N: CL201 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1579:2:1579:3|M
@W: CD604 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1629:6:1629:19|M
@W: CL169 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1640:2:1640:3|M
@TM:1368738943
@N:  :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":1971:2:1971:3|M
@N:  :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":2011:2:2011:3|M
@N:  :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":2020:2:2020:3|M
@N:  :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":2029:2:2029:3|M
@N:  :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":2038:2:2038:3|M
@N:  :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":2093:2:2093:3|M
@N:  :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":2178:2:2178:3|M
@N:  :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":2213:2:2213:3|M
@N:  :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":2213:2:2213:3|M
@TM:1368738924
@N: CL201 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":2213:2:2213:3|M
@W: CD604 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\ladder_fpga.vhd":2270:6:2270:19|M
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mega_func_fifo21x32_cycloneIII.vhd":42:7:42:36|M
@TM:1368738943
@W: MT246 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mega_func_fifo21x32_cycloneiii.vhd":99:1:99:16|M
@TM:1368738924
@N: NF117 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mega_func_fifo21x32_cycloneIII.vhd":99:1:99:16|M
@W: NF120 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mega_func_fifo21x32_cycloneIII.vhd":99:1:99:16|M
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mega_func_fifo8x256_cycloneIII.vhd":42:7:42:36|M
@TM:1368738943
@W: MT246 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mega_func_fifo8x256_cycloneiii.vhd":99:1:99:16|M
@TM:1368738924
@N: NF117 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mega_func_fifo8x256_cycloneIII.vhd":99:1:99:16|M
@W: NF120 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mega_func_fifo8x256_cycloneIII.vhd":99:1:99:16|M
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mega_func_pll_40MHz_switchover_cycloneIII.vhd":42:7:42:47|M
@TM:1368738943
@W: MT403 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mega_func_pll_40mhz_switchover_cycloneiii.vhd":182:1:182:16|M
@TM:1368738924
@N: NF117 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mega_func_pll_40MHz_switchover_cycloneIII.vhd":182:1:182:16|M
@W: NF120 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mega_func_pll_40MHz_switchover_cycloneIII.vhd":182:1:182:16|M
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\memoire_latchup.vhd":39:7:39:21|M
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\memoire_latchup_general.vhd":21:7:21:29|M
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\memoire_tokenout_echelle.vhd":22:7:22:30|M
@TM:1368738943
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\memoire_tokenout_echelle.vhd":46:22:46:23|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\memoire_tokenout_echelle.vhd":48:22:48:23|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\memoire_tokenout_echelle.vhd":50:22:50:23|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\memoire_tokenout_echelle.vhd":52:22:52:23|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\memoire_tokenout_echelle.vhd":54:22:54:23|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\memoire_tokenout_echelle.vhd":56:22:56:23|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\memoire_tokenout_echelle.vhd":58:22:58:23|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\memoire_tokenout_echelle.vhd":60:22:60:23|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\memoire_tokenout_echelle.vhd":62:22:62:23|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\memoire_tokenout_echelle.vhd":64:22:64:23|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\memoire_tokenout_echelle.vhd":66:22:66:23|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\memoire_tokenout_echelle.vhd":68:22:68:23|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\memoire_tokenout_echelle.vhd":70:22:70:23|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\memoire_tokenout_echelle.vhd":72:22:72:23|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\memoire_tokenout_echelle.vhd":74:22:74:23|M
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\memoire_tokenout_echelle.vhd":76:22:76:23|M
@TM:1368738924
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mesure_temperature.vhd":7:7:7:24|M
@N: CD231 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mesure_temperature.vhd":21:19:21:20|M
@TM:1368738943
@N:  :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mesure_temperature.vhd":50:6:50:7|M
@TM:1368738924
@W: CL169 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mesure_temperature.vhd":50:6:50:7|M
@W: CL169 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mesure_temperature.vhd":50:6:50:7|M
@W: CL190 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mesure_temperature.vhd":50:6:50:7|M
@N: CL201 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mesure_temperature.vhd":50:6:50:7|M
@W: CL249 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mesure_temperature.vhd":50:6:50:7|M
@A: CL282 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mesure_temperature.vhd":50:6:50:7|M
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mux_2_1.vhd":16:7:16:13|M
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\mux_tdo.vhd":31:7:31:13|M
@TM:1368738943
@W: MT447 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\rev_1\pin_assign.sdc":1:0:1:0|M
@TM:1368738927
@N:  :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\rev_1\synlog\ladder_fpga_fpga_mapper.srr":0:0:0:0|M
@TM:1368738925
@N:  :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\rev_1\synlog\ladder_fpga_premap.srr":0:0:0:0|M
@TM:1368738924
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\shiftreg.vhd":42:7:42:14|M
@TM:1368738943
@W: MT246 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\shiftreg.vhd":78:1:78:22|M
@TM:1368738924
@N: NF117 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\shiftreg.vhd":78:1:78:22|M
@W: NF120 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\shiftreg.vhd":78:1:78:22|M
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\signaux_hybrides.vhd":54:7:54:22|M
@TM:1368738943
@W: MT462 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\signaux_hybrides.vhd":89:9:89:10|M
@W: MT462 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\signaux_hybrides.vhd":89:9:89:10|M
@TM:1368738924
@N: CD630 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\tap_control.vhd":38:7:38:17|M
@N: CD231 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\tap_control.vhd":61:13:61:14|M
@N: CL201 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\tap_control.vhd":75:4:75:5|M
@W: CL249 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\tap_control.vhd":75:4:75:5|M
@W: CD604 :"D:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\tap_control.vhd":200:1:200:14|M
@TM:1368738943
@N: BN362 :"d:\renard\star_upgrade\doc_www\ts\ladder_fpga_v0d_20130514_ts\ladder_fpga_v0d\tap_control.vhd":216:2:216:3|M
