// megafunction wizard: %FIFO%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: dcfifo 

// ============================================================
// File Name: fifo8_copy.v
// Megafunction Name(s):
// 			dcfifo
//
// Simulation Library Files(s):
// 			
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 10.1 Build 197 01/19/2011 SP 1 SJ Full Version
// ************************************************************


//Copyright (C) 1991-2011 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


//dcfifo_mixed_widths DEVICE_FAMILY="Cyclone III" LPM_NUMWORDS=256 LPM_SHOWAHEAD="OFF" LPM_WIDTH=8 LPM_WIDTH_R=8 LPM_WIDTHU=8 LPM_WIDTHU_R=8 OVERFLOW_CHECKING="OFF" RDSYNC_DELAYPIPE=5 UNDERFLOW_CHECKING="OFF" USE_EAB="ON" WRITE_ACLR_SYNCH="OFF" WRSYNC_DELAYPIPE=5 aclr data q rdclk rdempty rdreq wrclk wrfull wrreq INTENDED_DEVICE_FAMILY="Cyclone III" ALTERA_INTERNAL_OPTIONS=AUTO_SHIFT_REGISTER_RECOGNITION=OFF
//VERSION_BEGIN 10.1SP1 cbx_a_gray2bin 2011:01:19:21:13:40:SJ cbx_a_graycounter 2011:01:19:21:13:40:SJ cbx_altdpram 2011:01:19:21:13:40:SJ cbx_altsyncram 2011:01:19:21:13:40:SJ cbx_cycloneii 2011:01:19:21:13:40:SJ cbx_dcfifo 2011:01:19:21:13:40:SJ cbx_fifo_common 2011:01:19:21:13:40:SJ cbx_lpm_add_sub 2011:01:19:21:13:40:SJ cbx_lpm_compare 2011:01:19:21:13:40:SJ cbx_lpm_counter 2011:01:19:21:13:40:SJ cbx_lpm_decode 2011:01:19:21:13:40:SJ cbx_lpm_mux 2011:01:19:21:13:40:SJ cbx_mgl 2011:01:19:21:15:40:SJ cbx_scfifo 2011:01:19:21:13:40:SJ cbx_stratix 2011:01:19:21:13:40:SJ cbx_stratixii 2011:01:19:21:13:40:SJ cbx_stratixiii 2011:01:19:21:13:40:SJ cbx_stratixv 2011:01:19:21:13:40:SJ cbx_util_mgl 2011:01:19:21:13:40:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463



//a_graycounter DEVICE_FAMILY="Cyclone III" PVALUE=1 WIDTH=9 aclr clock cnt_en q
//VERSION_BEGIN 10.1SP1 cbx_a_gray2bin 2011:01:19:21:13:40:SJ cbx_a_graycounter 2011:01:19:21:13:40:SJ cbx_cycloneii 2011:01:19:21:13:40:SJ cbx_mgl 2011:01:19:21:15:40:SJ cbx_stratix 2011:01:19:21:13:40:SJ cbx_stratixii 2011:01:19:21:13:40:SJ  VERSION_END

//synthesis_resources = reg 13 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"{-to counter5a[0]} POWER_UP_LEVEL=HIGH"} *)
module  fifo8_copy_a_graycounter
	( 
	aclr,
	clock,
	cnt_en,
	q) /* synthesis synthesis_clearbox=1 */;
	input   aclr;
	input   clock;
	input   cnt_en;
	output   [8:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr;
	tri1   cnt_en;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[8:0]	counter5a;
	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=HIGH"} *)
	reg	parity6;
	reg	[2:0]	sub_parity7a;
	wire  [8:0]  cntr_cout;
	wire  parity_cout;
	wire sclr;
	wire updown;

	// synopsys translate_off
	initial
		counter5a[0:0] = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[0:0] <= {1{1'b1}};
		else
			if (sclr == 1'b1) counter5a[0:0] <= 1'b0;
			else  counter5a[0:0] <= ((cnt_en & (counter5a[0:0] ^ (~ parity_cout))) | ((~ cnt_en) & counter5a[0:0]));
	// synopsys translate_off
	initial
		counter5a[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[1:1] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[1:1] <= 1'b0;
			else  counter5a[1:1] <= (counter5a[1:1] ^ (counter5a[0:0] & cntr_cout[0]));
	// synopsys translate_off
	initial
		counter5a[2:2] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[2:2] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[2:2] <= 1'b0;
			else  counter5a[2:2] <= (counter5a[2:2] ^ (counter5a[1:1] & cntr_cout[1]));
	// synopsys translate_off
	initial
		counter5a[3:3] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[3:3] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[3:3] <= 1'b0;
			else  counter5a[3:3] <= (counter5a[3:3] ^ (counter5a[2:2] & cntr_cout[2]));
	// synopsys translate_off
	initial
		counter5a[4:4] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[4:4] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[4:4] <= 1'b0;
			else  counter5a[4:4] <= (counter5a[4:4] ^ (counter5a[3:3] & cntr_cout[3]));
	// synopsys translate_off
	initial
		counter5a[5:5] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[5:5] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[5:5] <= 1'b0;
			else  counter5a[5:5] <= (counter5a[5:5] ^ (counter5a[4:4] & cntr_cout[4]));
	// synopsys translate_off
	initial
		counter5a[6:6] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[6:6] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[6:6] <= 1'b0;
			else  counter5a[6:6] <= (counter5a[6:6] ^ (counter5a[5:5] & cntr_cout[5]));
	// synopsys translate_off
	initial
		counter5a[7:7] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[7:7] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[7:7] <= 1'b0;
			else  counter5a[7:7] <= (counter5a[7:7] ^ (counter5a[6:6] & cntr_cout[6]));
	// synopsys translate_off
	initial
		counter5a[8:8] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[8:8] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[8:8] <= 1'b0;
			else  counter5a[8:8] <= (counter5a[8:8] ^ cntr_cout[7]);
	// synopsys translate_off
	initial
		parity6 = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) parity6 <= {1{1'b1}};
		else
			if (sclr == 1'b1) parity6 <= 1'b0;
			else  parity6 <= ((cnt_en & ((sub_parity7a[0] ^ sub_parity7a[1]) ^ sub_parity7a[2])) | ((~ cnt_en) & parity6));
	// synopsys translate_off
	initial
		sub_parity7a[0:0] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sub_parity7a[0:0] <= 1'b0;
		else
			if (sclr == 1'b1) sub_parity7a[0:0] <= 1'b0;
			else  sub_parity7a[0:0] <= ((cnt_en & (((counter5a[0] ^ counter5a[1]) ^ counter5a[2]) ^ counter5a[3])) | ((~ cnt_en) & sub_parity7a[0:0]));
	// synopsys translate_off
	initial
		sub_parity7a[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sub_parity7a[1:1] <= 1'b0;
		else
			if (sclr == 1'b1) sub_parity7a[1:1] <= 1'b0;
			else  sub_parity7a[1:1] <= ((cnt_en & (((counter5a[4] ^ counter5a[5]) ^ counter5a[6]) ^ counter5a[7])) | ((~ cnt_en) & sub_parity7a[1:1]));
	// synopsys translate_off
	initial
		sub_parity7a[2:2] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sub_parity7a[2:2] <= 1'b0;
		else
			if (sclr == 1'b1) sub_parity7a[2:2] <= 1'b0;
			else  sub_parity7a[2:2] <= ((cnt_en & counter5a[8]) | ((~ cnt_en) & sub_parity7a[2:2]));
	assign
		cntr_cout = {1'b0, (cntr_cout[6] & (~ counter5a[6:6])), (cntr_cout[5] & (~ counter5a[5:5])), (cntr_cout[4] & (~ counter5a[4:4])), (cntr_cout[3] & (~ counter5a[3:3])), (cntr_cout[2] & (~ counter5a[2:2])), (cntr_cout[1] & (~ counter5a[1:1])), (cntr_cout[0] & (~ counter5a[0:0])), (cnt_en & parity_cout)},
		parity_cout = (((~ parity6) ^ updown) & cnt_en),
		q = counter5a,
		sclr = 1'b0,
		updown = 1'b1;
endmodule //fifo8_copy_a_graycounter


//a_graycounter DEVICE_FAMILY="Cyclone III" PVALUE=1 WIDTH=9 aclr clock cnt_en q ALTERA_INTERNAL_OPTIONS=suppress_da_rule_internal=S102
//VERSION_BEGIN 10.1SP1 cbx_a_gray2bin 2011:01:19:21:13:40:SJ cbx_a_graycounter 2011:01:19:21:13:40:SJ cbx_cycloneii 2011:01:19:21:13:40:SJ cbx_mgl 2011:01:19:21:15:40:SJ cbx_stratix 2011:01:19:21:13:40:SJ cbx_stratixii 2011:01:19:21:13:40:SJ  VERSION_END

//synthesis_resources = reg 13 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"suppress_da_rule_internal=S102;{-to counter8a[0]} POWER_UP_LEVEL=HIGH"} *)
module  fifo8_copy_a_graycounter1
	( 
	aclr,
	clock,
	cnt_en,
	q) /* synthesis synthesis_clearbox=1 */;
	input   aclr;
	input   clock;
	input   cnt_en;
	output   [8:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr;
	tri1   cnt_en;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[8:0]	counter8a;
	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=HIGH"} *)
	reg	parity9;
	reg	[2:0]	sub_parity10a;
	wire  [8:0]  cntr_cout;
	wire  parity_cout;
	wire sclr;
	wire updown;

	// synopsys translate_off
	initial
		counter8a[0:0] = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter8a[0:0] <= {1{1'b1}};
		else
			if (sclr == 1'b1) counter8a[0:0] <= 1'b0;
			else  counter8a[0:0] <= ((cnt_en & (counter8a[0:0] ^ (~ parity_cout))) | ((~ cnt_en) & counter8a[0:0]));
	// synopsys translate_off
	initial
		counter8a[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter8a[1:1] <= 1'b0;
		else
			if (sclr == 1'b1) counter8a[1:1] <= 1'b0;
			else  counter8a[1:1] <= (counter8a[1:1] ^ (counter8a[0:0] & cntr_cout[0]));
	// synopsys translate_off
	initial
		counter8a[2:2] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter8a[2:2] <= 1'b0;
		else
			if (sclr == 1'b1) counter8a[2:2] <= 1'b0;
			else  counter8a[2:2] <= (counter8a[2:2] ^ (counter8a[1:1] & cntr_cout[1]));
	// synopsys translate_off
	initial
		counter8a[3:3] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter8a[3:3] <= 1'b0;
		else
			if (sclr == 1'b1) counter8a[3:3] <= 1'b0;
			else  counter8a[3:3] <= (counter8a[3:3] ^ (counter8a[2:2] & cntr_cout[2]));
	// synopsys translate_off
	initial
		counter8a[4:4] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter8a[4:4] <= 1'b0;
		else
			if (sclr == 1'b1) counter8a[4:4] <= 1'b0;
			else  counter8a[4:4] <= (counter8a[4:4] ^ (counter8a[3:3] & cntr_cout[3]));
	// synopsys translate_off
	initial
		counter8a[5:5] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter8a[5:5] <= 1'b0;
		else
			if (sclr == 1'b1) counter8a[5:5] <= 1'b0;
			else  counter8a[5:5] <= (counter8a[5:5] ^ (counter8a[4:4] & cntr_cout[4]));
	// synopsys translate_off
	initial
		counter8a[6:6] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter8a[6:6] <= 1'b0;
		else
			if (sclr == 1'b1) counter8a[6:6] <= 1'b0;
			else  counter8a[6:6] <= (counter8a[6:6] ^ (counter8a[5:5] & cntr_cout[5]));
	// synopsys translate_off
	initial
		counter8a[7:7] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter8a[7:7] <= 1'b0;
		else
			if (sclr == 1'b1) counter8a[7:7] <= 1'b0;
			else  counter8a[7:7] <= (counter8a[7:7] ^ (counter8a[6:6] & cntr_cout[6]));
	// synopsys translate_off
	initial
		counter8a[8:8] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter8a[8:8] <= 1'b0;
		else
			if (sclr == 1'b1) counter8a[8:8] <= 1'b0;
			else  counter8a[8:8] <= (counter8a[8:8] ^ cntr_cout[7]);
	// synopsys translate_off
	initial
		parity9 = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) parity9 <= {1{1'b1}};
		else
			if (sclr == 1'b1) parity9 <= 1'b0;
			else  parity9 <= ((cnt_en & ((sub_parity10a[0] ^ sub_parity10a[1]) ^ sub_parity10a[2])) | ((~ cnt_en) & parity9));
	// synopsys translate_off
	initial
		sub_parity10a[0:0] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sub_parity10a[0:0] <= 1'b0;
		else
			if (sclr == 1'b1) sub_parity10a[0:0] <= 1'b0;
			else  sub_parity10a[0:0] <= ((cnt_en & (((counter8a[0] ^ counter8a[1]) ^ counter8a[2]) ^ counter8a[3])) | ((~ cnt_en) & sub_parity10a[0:0]));
	// synopsys translate_off
	initial
		sub_parity10a[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sub_parity10a[1:1] <= 1'b0;
		else
			if (sclr == 1'b1) sub_parity10a[1:1] <= 1'b0;
			else  sub_parity10a[1:1] <= ((cnt_en & (((counter8a[4] ^ counter8a[5]) ^ counter8a[6]) ^ counter8a[7])) | ((~ cnt_en) & sub_parity10a[1:1]));
	// synopsys translate_off
	initial
		sub_parity10a[2:2] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sub_parity10a[2:2] <= 1'b0;
		else
			if (sclr == 1'b1) sub_parity10a[2:2] <= 1'b0;
			else  sub_parity10a[2:2] <= ((cnt_en & counter8a[8]) | ((~ cnt_en) & sub_parity10a[2:2]));
	assign
		cntr_cout = {1'b0, (cntr_cout[6] & (~ counter8a[6:6])), (cntr_cout[5] & (~ counter8a[5:5])), (cntr_cout[4] & (~ counter8a[4:4])), (cntr_cout[3] & (~ counter8a[3:3])), (cntr_cout[2] & (~ counter8a[2:2])), (cntr_cout[1] & (~ counter8a[1:1])), (cntr_cout[0] & (~ counter8a[0:0])), (cnt_en & parity_cout)},
		parity_cout = (((~ parity9) ^ updown) & cnt_en),
		q = counter8a,
		sclr = 1'b0,
		updown = 1'b1;
endmodule //fifo8_copy_a_graycounter1


//a_graycounter DEVICE_FAMILY="Cyclone III" PVALUE=0 WIDTH=9 aclr clock cnt_en q ALTERA_INTERNAL_OPTIONS=suppress_da_rule_internal=S102
//VERSION_BEGIN 10.1SP1 cbx_a_gray2bin 2011:01:19:21:13:40:SJ cbx_a_graycounter 2011:01:19:21:13:40:SJ cbx_cycloneii 2011:01:19:21:13:40:SJ cbx_mgl 2011:01:19:21:15:40:SJ cbx_stratix 2011:01:19:21:13:40:SJ cbx_stratixii 2011:01:19:21:13:40:SJ  VERSION_END

//synthesis_resources = reg 13 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"suppress_da_rule_internal=S102;{-to sub_parity12a[0]} POWER_UP_LEVEL=HIGH"} *)
module  fifo8_copy_a_graycounter12
	( 
	aclr,
	clock,
	cnt_en,
	q) /* synthesis synthesis_clearbox=1 */;
	input   aclr;
	input   clock;
	input   cnt_en;
	output   [8:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr;
	tri1   cnt_en;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[8:0]	counter13a;
	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=LOW"} *)
	reg	parity11;
	reg	[2:0]	sub_parity12a;
	wire  [8:0]  cntr_cout;
	wire  parity_cout;
	wire sclr;
	wire updown;

	// synopsys translate_off
	initial
		counter13a[0:0] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter13a[0:0] <= 1'b0;
		else
			if (sclr == 1'b1) counter13a[0:0] <= 1'b0;
			else  counter13a[0:0] <= ((cnt_en & (counter13a[0:0] ^ (~ parity_cout))) | ((~ cnt_en) & counter13a[0:0]));
	// synopsys translate_off
	initial
		counter13a[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter13a[1:1] <= 1'b0;
		else
			if (sclr == 1'b1) counter13a[1:1] <= 1'b0;
			else  counter13a[1:1] <= (counter13a[1:1] ^ (counter13a[0:0] & cntr_cout[0]));
	// synopsys translate_off
	initial
		counter13a[2:2] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter13a[2:2] <= 1'b0;
		else
			if (sclr == 1'b1) counter13a[2:2] <= 1'b0;
			else  counter13a[2:2] <= (counter13a[2:2] ^ (counter13a[1:1] & cntr_cout[1]));
	// synopsys translate_off
	initial
		counter13a[3:3] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter13a[3:3] <= 1'b0;
		else
			if (sclr == 1'b1) counter13a[3:3] <= 1'b0;
			else  counter13a[3:3] <= (counter13a[3:3] ^ (counter13a[2:2] & cntr_cout[2]));
	// synopsys translate_off
	initial
		counter13a[4:4] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter13a[4:4] <= 1'b0;
		else
			if (sclr == 1'b1) counter13a[4:4] <= 1'b0;
			else  counter13a[4:4] <= (counter13a[4:4] ^ (counter13a[3:3] & cntr_cout[3]));
	// synopsys translate_off
	initial
		counter13a[5:5] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter13a[5:5] <= 1'b0;
		else
			if (sclr == 1'b1) counter13a[5:5] <= 1'b0;
			else  counter13a[5:5] <= (counter13a[5:5] ^ (counter13a[4:4] & cntr_cout[4]));
	// synopsys translate_off
	initial
		counter13a[6:6] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter13a[6:6] <= 1'b0;
		else
			if (sclr == 1'b1) counter13a[6:6] <= 1'b0;
			else  counter13a[6:6] <= (counter13a[6:6] ^ (counter13a[5:5] & cntr_cout[5]));
	// synopsys translate_off
	initial
		counter13a[7:7] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter13a[7:7] <= 1'b0;
		else
			if (sclr == 1'b1) counter13a[7:7] <= 1'b0;
			else  counter13a[7:7] <= (counter13a[7:7] ^ (counter13a[6:6] & cntr_cout[6]));
	// synopsys translate_off
	initial
		counter13a[8:8] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter13a[8:8] <= 1'b0;
		else
			if (sclr == 1'b1) counter13a[8:8] <= 1'b0;
			else  counter13a[8:8] <= (counter13a[8:8] ^ cntr_cout[7]);
	// synopsys translate_off
	initial
		parity11 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) parity11 <= 1'b0;
		else
			if (sclr == 1'b1) parity11 <= 1'b0;
			else  parity11 <= ((cnt_en & ((sub_parity12a[0] ^ sub_parity12a[1]) ^ sub_parity12a[2])) | ((~ cnt_en) & parity11));
	// synopsys translate_off
	initial
		sub_parity12a[0:0] = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sub_parity12a[0:0] <= {1{1'b1}};
		else
			if (sclr == 1'b1) sub_parity12a[0:0] <= 1'b0;
			else  sub_parity12a[0:0] <= ((cnt_en & (((counter13a[0] ^ counter13a[1]) ^ counter13a[2]) ^ counter13a[3])) | ((~ cnt_en) & sub_parity12a[0:0]));
	// synopsys translate_off
	initial
		sub_parity12a[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sub_parity12a[1:1] <= 1'b0;
		else
			if (sclr == 1'b1) sub_parity12a[1:1] <= 1'b0;
			else  sub_parity12a[1:1] <= ((cnt_en & (((counter13a[4] ^ counter13a[5]) ^ counter13a[6]) ^ counter13a[7])) | ((~ cnt_en) & sub_parity12a[1:1]));
	// synopsys translate_off
	initial
		sub_parity12a[2:2] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sub_parity12a[2:2] <= 1'b0;
		else
			if (sclr == 1'b1) sub_parity12a[2:2] <= 1'b0;
			else  sub_parity12a[2:2] <= ((cnt_en & counter13a[8]) | ((~ cnt_en) & sub_parity12a[2:2]));
	assign
		cntr_cout = {1'b0, (cntr_cout[6] & (~ counter13a[6:6])), (cntr_cout[5] & (~ counter13a[5:5])), (cntr_cout[4] & (~ counter13a[4:4])), (cntr_cout[3] & (~ counter13a[3:3])), (cntr_cout[2] & (~ counter13a[2:2])), (cntr_cout[1] & (~ counter13a[1:1])), (cntr_cout[0] & (~ counter13a[0:0])), (cnt_en & parity_cout)},
		parity_cout = ((parity11 ^ (~ updown)) & cnt_en),
		q = counter13a,
		sclr = 1'b0,
		updown = 1'b1;
endmodule //fifo8_copy_a_graycounter12


//altsyncram ADDRESS_ACLR_B="CLEAR1" ADDRESS_REG_B="CLOCK1" CLOCK_ENABLE_INPUT_B="BYPASS" DEVICE_FAMILY="Cyclone III" OPERATION_MODE="DUAL_PORT" OUTDATA_ACLR_B="CLEAR1" OUTDATA_REG_B="CLOCK1" WIDTH_A=8 WIDTH_B=8 WIDTH_BYTEENA_A=1 WIDTHAD_A=8 WIDTHAD_B=8 aclr1 address_a address_b addressstall_b clock0 clock1 clocken1 data_a q_b wren_a
//VERSION_BEGIN 10.1SP1 cbx_altsyncram 2011:01:19:21:13:40:SJ cbx_cycloneii 2011:01:19:21:13:40:SJ cbx_lpm_add_sub 2011:01:19:21:13:40:SJ cbx_lpm_compare 2011:01:19:21:13:40:SJ cbx_lpm_decode 2011:01:19:21:13:40:SJ cbx_lpm_mux 2011:01:19:21:13:40:SJ cbx_mgl 2011:01:19:21:15:40:SJ cbx_stratix 2011:01:19:21:13:40:SJ cbx_stratixii 2011:01:19:21:13:40:SJ cbx_stratixiii 2011:01:19:21:13:40:SJ cbx_stratixv 2011:01:19:21:13:40:SJ cbx_util_mgl 2011:01:19:21:13:40:SJ  VERSION_END

//synthesis_resources = M9K 1 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"OPTIMIZE_POWER_DURING_SYNTHESIS=NORMAL_COMPILATION"} *)
module  fifo8_copy_altsyncram
	( 
	aclr1,
	address_a,
	address_b,
	addressstall_b,
	clock0,
	clock1,
	clocken1,
	data_a,
	q_b,
	wren_a) /* synthesis synthesis_clearbox=1 */;
	input   aclr1;
	input   [7:0]  address_a;
	input   [7:0]  address_b;
	input   addressstall_b;
	input   clock0;
	input   clock1;
	input   clocken1;
	input   [7:0]  data_a;
	output   [7:0]  q_b;
	input   wren_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr1;
	tri1   [7:0]  address_b;
	tri0   addressstall_b;
	tri1   clock0;
	tri1   clock1;
	tri1   clocken1;
	tri1   [7:0]  data_a;
	tri0   wren_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]   wire_ram_block14a_0portbdataout;
	wire  [0:0]   wire_ram_block14a_1portbdataout;
	wire  [0:0]   wire_ram_block14a_2portbdataout;
	wire  [0:0]   wire_ram_block14a_3portbdataout;
	wire  [0:0]   wire_ram_block14a_4portbdataout;
	wire  [0:0]   wire_ram_block14a_5portbdataout;
	wire  [0:0]   wire_ram_block14a_6portbdataout;
	wire  [0:0]   wire_ram_block14a_7portbdataout;
	wire  [7:0]  address_a_wire;
	wire  [7:0]  address_b_wire;

	cycloneiii_ram_block   ram_block14a_0
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[0]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block14a_0portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block14a_0.clk0_core_clock_enable = "ena0",
		ram_block14a_0.clk0_input_clock_enable = "none",
		ram_block14a_0.clk1_core_clock_enable = "none",
		ram_block14a_0.clk1_input_clock_enable = "none",
		ram_block14a_0.clk1_output_clock_enable = "ena1",
		ram_block14a_0.connectivity_checking = "OFF",
		ram_block14a_0.logical_ram_name = "ALTSYNCRAM",
		ram_block14a_0.mixed_port_feed_through_mode = "dont_care",
		ram_block14a_0.operation_mode = "dual_port",
		ram_block14a_0.port_a_address_width = 8,
		ram_block14a_0.port_a_data_width = 1,
		ram_block14a_0.port_a_first_address = 0,
		ram_block14a_0.port_a_first_bit_number = 0,
		ram_block14a_0.port_a_last_address = 255,
		ram_block14a_0.port_a_logical_ram_depth = 256,
		ram_block14a_0.port_a_logical_ram_width = 8,
		ram_block14a_0.port_b_address_clear = "clear1",
		ram_block14a_0.port_b_address_clock = "clock1",
		ram_block14a_0.port_b_address_width = 8,
		ram_block14a_0.port_b_data_out_clear = "clear1",
		ram_block14a_0.port_b_data_out_clock = "clock1",
		ram_block14a_0.port_b_data_width = 1,
		ram_block14a_0.port_b_first_address = 0,
		ram_block14a_0.port_b_first_bit_number = 0,
		ram_block14a_0.port_b_last_address = 255,
		ram_block14a_0.port_b_logical_ram_depth = 256,
		ram_block14a_0.port_b_logical_ram_width = 8,
		ram_block14a_0.port_b_read_enable_clock = "clock1",
		ram_block14a_0.ram_block_type = "AUTO",
		ram_block14a_0.lpm_type = "cycloneiii_ram_block";
	cycloneiii_ram_block   ram_block14a_1
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[1]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block14a_1portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block14a_1.clk0_core_clock_enable = "ena0",
		ram_block14a_1.clk0_input_clock_enable = "none",
		ram_block14a_1.clk1_core_clock_enable = "none",
		ram_block14a_1.clk1_input_clock_enable = "none",
		ram_block14a_1.clk1_output_clock_enable = "ena1",
		ram_block14a_1.connectivity_checking = "OFF",
		ram_block14a_1.logical_ram_name = "ALTSYNCRAM",
		ram_block14a_1.mixed_port_feed_through_mode = "dont_care",
		ram_block14a_1.operation_mode = "dual_port",
		ram_block14a_1.port_a_address_width = 8,
		ram_block14a_1.port_a_data_width = 1,
		ram_block14a_1.port_a_first_address = 0,
		ram_block14a_1.port_a_first_bit_number = 1,
		ram_block14a_1.port_a_last_address = 255,
		ram_block14a_1.port_a_logical_ram_depth = 256,
		ram_block14a_1.port_a_logical_ram_width = 8,
		ram_block14a_1.port_b_address_clear = "clear1",
		ram_block14a_1.port_b_address_clock = "clock1",
		ram_block14a_1.port_b_address_width = 8,
		ram_block14a_1.port_b_data_out_clear = "clear1",
		ram_block14a_1.port_b_data_out_clock = "clock1",
		ram_block14a_1.port_b_data_width = 1,
		ram_block14a_1.port_b_first_address = 0,
		ram_block14a_1.port_b_first_bit_number = 1,
		ram_block14a_1.port_b_last_address = 255,
		ram_block14a_1.port_b_logical_ram_depth = 256,
		ram_block14a_1.port_b_logical_ram_width = 8,
		ram_block14a_1.port_b_read_enable_clock = "clock1",
		ram_block14a_1.ram_block_type = "AUTO",
		ram_block14a_1.lpm_type = "cycloneiii_ram_block";
	cycloneiii_ram_block   ram_block14a_2
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[2]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block14a_2portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block14a_2.clk0_core_clock_enable = "ena0",
		ram_block14a_2.clk0_input_clock_enable = "none",
		ram_block14a_2.clk1_core_clock_enable = "none",
		ram_block14a_2.clk1_input_clock_enable = "none",
		ram_block14a_2.clk1_output_clock_enable = "ena1",
		ram_block14a_2.connectivity_checking = "OFF",
		ram_block14a_2.logical_ram_name = "ALTSYNCRAM",
		ram_block14a_2.mixed_port_feed_through_mode = "dont_care",
		ram_block14a_2.operation_mode = "dual_port",
		ram_block14a_2.port_a_address_width = 8,
		ram_block14a_2.port_a_data_width = 1,
		ram_block14a_2.port_a_first_address = 0,
		ram_block14a_2.port_a_first_bit_number = 2,
		ram_block14a_2.port_a_last_address = 255,
		ram_block14a_2.port_a_logical_ram_depth = 256,
		ram_block14a_2.port_a_logical_ram_width = 8,
		ram_block14a_2.port_b_address_clear = "clear1",
		ram_block14a_2.port_b_address_clock = "clock1",
		ram_block14a_2.port_b_address_width = 8,
		ram_block14a_2.port_b_data_out_clear = "clear1",
		ram_block14a_2.port_b_data_out_clock = "clock1",
		ram_block14a_2.port_b_data_width = 1,
		ram_block14a_2.port_b_first_address = 0,
		ram_block14a_2.port_b_first_bit_number = 2,
		ram_block14a_2.port_b_last_address = 255,
		ram_block14a_2.port_b_logical_ram_depth = 256,
		ram_block14a_2.port_b_logical_ram_width = 8,
		ram_block14a_2.port_b_read_enable_clock = "clock1",
		ram_block14a_2.ram_block_type = "AUTO",
		ram_block14a_2.lpm_type = "cycloneiii_ram_block";
	cycloneiii_ram_block   ram_block14a_3
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[3]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block14a_3portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block14a_3.clk0_core_clock_enable = "ena0",
		ram_block14a_3.clk0_input_clock_enable = "none",
		ram_block14a_3.clk1_core_clock_enable = "none",
		ram_block14a_3.clk1_input_clock_enable = "none",
		ram_block14a_3.clk1_output_clock_enable = "ena1",
		ram_block14a_3.connectivity_checking = "OFF",
		ram_block14a_3.logical_ram_name = "ALTSYNCRAM",
		ram_block14a_3.mixed_port_feed_through_mode = "dont_care",
		ram_block14a_3.operation_mode = "dual_port",
		ram_block14a_3.port_a_address_width = 8,
		ram_block14a_3.port_a_data_width = 1,
		ram_block14a_3.port_a_first_address = 0,
		ram_block14a_3.port_a_first_bit_number = 3,
		ram_block14a_3.port_a_last_address = 255,
		ram_block14a_3.port_a_logical_ram_depth = 256,
		ram_block14a_3.port_a_logical_ram_width = 8,
		ram_block14a_3.port_b_address_clear = "clear1",
		ram_block14a_3.port_b_address_clock = "clock1",
		ram_block14a_3.port_b_address_width = 8,
		ram_block14a_3.port_b_data_out_clear = "clear1",
		ram_block14a_3.port_b_data_out_clock = "clock1",
		ram_block14a_3.port_b_data_width = 1,
		ram_block14a_3.port_b_first_address = 0,
		ram_block14a_3.port_b_first_bit_number = 3,
		ram_block14a_3.port_b_last_address = 255,
		ram_block14a_3.port_b_logical_ram_depth = 256,
		ram_block14a_3.port_b_logical_ram_width = 8,
		ram_block14a_3.port_b_read_enable_clock = "clock1",
		ram_block14a_3.ram_block_type = "AUTO",
		ram_block14a_3.lpm_type = "cycloneiii_ram_block";
	cycloneiii_ram_block   ram_block14a_4
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[4]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block14a_4portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block14a_4.clk0_core_clock_enable = "ena0",
		ram_block14a_4.clk0_input_clock_enable = "none",
		ram_block14a_4.clk1_core_clock_enable = "none",
		ram_block14a_4.clk1_input_clock_enable = "none",
		ram_block14a_4.clk1_output_clock_enable = "ena1",
		ram_block14a_4.connectivity_checking = "OFF",
		ram_block14a_4.logical_ram_name = "ALTSYNCRAM",
		ram_block14a_4.mixed_port_feed_through_mode = "dont_care",
		ram_block14a_4.operation_mode = "dual_port",
		ram_block14a_4.port_a_address_width = 8,
		ram_block14a_4.port_a_data_width = 1,
		ram_block14a_4.port_a_first_address = 0,
		ram_block14a_4.port_a_first_bit_number = 4,
		ram_block14a_4.port_a_last_address = 255,
		ram_block14a_4.port_a_logical_ram_depth = 256,
		ram_block14a_4.port_a_logical_ram_width = 8,
		ram_block14a_4.port_b_address_clear = "clear1",
		ram_block14a_4.port_b_address_clock = "clock1",
		ram_block14a_4.port_b_address_width = 8,
		ram_block14a_4.port_b_data_out_clear = "clear1",
		ram_block14a_4.port_b_data_out_clock = "clock1",
		ram_block14a_4.port_b_data_width = 1,
		ram_block14a_4.port_b_first_address = 0,
		ram_block14a_4.port_b_first_bit_number = 4,
		ram_block14a_4.port_b_last_address = 255,
		ram_block14a_4.port_b_logical_ram_depth = 256,
		ram_block14a_4.port_b_logical_ram_width = 8,
		ram_block14a_4.port_b_read_enable_clock = "clock1",
		ram_block14a_4.ram_block_type = "AUTO",
		ram_block14a_4.lpm_type = "cycloneiii_ram_block";
	cycloneiii_ram_block   ram_block14a_5
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[5]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block14a_5portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block14a_5.clk0_core_clock_enable = "ena0",
		ram_block14a_5.clk0_input_clock_enable = "none",
		ram_block14a_5.clk1_core_clock_enable = "none",
		ram_block14a_5.clk1_input_clock_enable = "none",
		ram_block14a_5.clk1_output_clock_enable = "ena1",
		ram_block14a_5.connectivity_checking = "OFF",
		ram_block14a_5.logical_ram_name = "ALTSYNCRAM",
		ram_block14a_5.mixed_port_feed_through_mode = "dont_care",
		ram_block14a_5.operation_mode = "dual_port",
		ram_block14a_5.port_a_address_width = 8,
		ram_block14a_5.port_a_data_width = 1,
		ram_block14a_5.port_a_first_address = 0,
		ram_block14a_5.port_a_first_bit_number = 5,
		ram_block14a_5.port_a_last_address = 255,
		ram_block14a_5.port_a_logical_ram_depth = 256,
		ram_block14a_5.port_a_logical_ram_width = 8,
		ram_block14a_5.port_b_address_clear = "clear1",
		ram_block14a_5.port_b_address_clock = "clock1",
		ram_block14a_5.port_b_address_width = 8,
		ram_block14a_5.port_b_data_out_clear = "clear1",
		ram_block14a_5.port_b_data_out_clock = "clock1",
		ram_block14a_5.port_b_data_width = 1,
		ram_block14a_5.port_b_first_address = 0,
		ram_block14a_5.port_b_first_bit_number = 5,
		ram_block14a_5.port_b_last_address = 255,
		ram_block14a_5.port_b_logical_ram_depth = 256,
		ram_block14a_5.port_b_logical_ram_width = 8,
		ram_block14a_5.port_b_read_enable_clock = "clock1",
		ram_block14a_5.ram_block_type = "AUTO",
		ram_block14a_5.lpm_type = "cycloneiii_ram_block";
	cycloneiii_ram_block   ram_block14a_6
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[6]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block14a_6portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block14a_6.clk0_core_clock_enable = "ena0",
		ram_block14a_6.clk0_input_clock_enable = "none",
		ram_block14a_6.clk1_core_clock_enable = "none",
		ram_block14a_6.clk1_input_clock_enable = "none",
		ram_block14a_6.clk1_output_clock_enable = "ena1",
		ram_block14a_6.connectivity_checking = "OFF",
		ram_block14a_6.logical_ram_name = "ALTSYNCRAM",
		ram_block14a_6.mixed_port_feed_through_mode = "dont_care",
		ram_block14a_6.operation_mode = "dual_port",
		ram_block14a_6.port_a_address_width = 8,
		ram_block14a_6.port_a_data_width = 1,
		ram_block14a_6.port_a_first_address = 0,
		ram_block14a_6.port_a_first_bit_number = 6,
		ram_block14a_6.port_a_last_address = 255,
		ram_block14a_6.port_a_logical_ram_depth = 256,
		ram_block14a_6.port_a_logical_ram_width = 8,
		ram_block14a_6.port_b_address_clear = "clear1",
		ram_block14a_6.port_b_address_clock = "clock1",
		ram_block14a_6.port_b_address_width = 8,
		ram_block14a_6.port_b_data_out_clear = "clear1",
		ram_block14a_6.port_b_data_out_clock = "clock1",
		ram_block14a_6.port_b_data_width = 1,
		ram_block14a_6.port_b_first_address = 0,
		ram_block14a_6.port_b_first_bit_number = 6,
		ram_block14a_6.port_b_last_address = 255,
		ram_block14a_6.port_b_logical_ram_depth = 256,
		ram_block14a_6.port_b_logical_ram_width = 8,
		ram_block14a_6.port_b_read_enable_clock = "clock1",
		ram_block14a_6.ram_block_type = "AUTO",
		ram_block14a_6.lpm_type = "cycloneiii_ram_block";
	cycloneiii_ram_block   ram_block14a_7
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[7]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block14a_7portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block14a_7.clk0_core_clock_enable = "ena0",
		ram_block14a_7.clk0_input_clock_enable = "none",
		ram_block14a_7.clk1_core_clock_enable = "none",
		ram_block14a_7.clk1_input_clock_enable = "none",
		ram_block14a_7.clk1_output_clock_enable = "ena1",
		ram_block14a_7.connectivity_checking = "OFF",
		ram_block14a_7.logical_ram_name = "ALTSYNCRAM",
		ram_block14a_7.mixed_port_feed_through_mode = "dont_care",
		ram_block14a_7.operation_mode = "dual_port",
		ram_block14a_7.port_a_address_width = 8,
		ram_block14a_7.port_a_data_width = 1,
		ram_block14a_7.port_a_first_address = 0,
		ram_block14a_7.port_a_first_bit_number = 7,
		ram_block14a_7.port_a_last_address = 255,
		ram_block14a_7.port_a_logical_ram_depth = 256,
		ram_block14a_7.port_a_logical_ram_width = 8,
		ram_block14a_7.port_b_address_clear = "clear1",
		ram_block14a_7.port_b_address_clock = "clock1",
		ram_block14a_7.port_b_address_width = 8,
		ram_block14a_7.port_b_data_out_clear = "clear1",
		ram_block14a_7.port_b_data_out_clock = "clock1",
		ram_block14a_7.port_b_data_width = 1,
		ram_block14a_7.port_b_first_address = 0,
		ram_block14a_7.port_b_first_bit_number = 7,
		ram_block14a_7.port_b_last_address = 255,
		ram_block14a_7.port_b_logical_ram_depth = 256,
		ram_block14a_7.port_b_logical_ram_width = 8,
		ram_block14a_7.port_b_read_enable_clock = "clock1",
		ram_block14a_7.ram_block_type = "AUTO",
		ram_block14a_7.lpm_type = "cycloneiii_ram_block";
	assign
		address_a_wire = address_a,
		address_b_wire = address_b,
		q_b = {wire_ram_block14a_7portbdataout[0], wire_ram_block14a_6portbdataout[0], wire_ram_block14a_5portbdataout[0], wire_ram_block14a_4portbdataout[0], wire_ram_block14a_3portbdataout[0], wire_ram_block14a_2portbdataout[0], wire_ram_block14a_1portbdataout[0], wire_ram_block14a_0portbdataout[0]};
endmodule //fifo8_copy_altsyncram


//dffpipe DELAY=2 WIDTH=9 clock clrn d q ALTERA_INTERNAL_OPTIONS=X_ON_VIOLATION_OPTION=OFF;SYNCHRONIZER_IDENTIFICATION=FORCED_IF_ASYNCHRONOUS
//VERSION_BEGIN 10.1SP1 cbx_a_gray2bin 2011:01:19:21:13:40:SJ cbx_a_graycounter 2011:01:19:21:13:40:SJ cbx_altdpram 2011:01:19:21:13:40:SJ cbx_altsyncram 2011:01:19:21:13:40:SJ cbx_cycloneii 2011:01:19:21:13:40:SJ cbx_dcfifo 2011:01:19:21:13:40:SJ cbx_fifo_common 2011:01:19:21:13:40:SJ cbx_lpm_add_sub 2011:01:19:21:13:40:SJ cbx_lpm_compare 2011:01:19:21:13:40:SJ cbx_lpm_counter 2011:01:19:21:13:40:SJ cbx_lpm_decode 2011:01:19:21:13:40:SJ cbx_lpm_mux 2011:01:19:21:13:40:SJ cbx_mgl 2011:01:19:21:15:40:SJ cbx_scfifo 2011:01:19:21:13:40:SJ cbx_stratix 2011:01:19:21:13:40:SJ cbx_stratixii 2011:01:19:21:13:40:SJ cbx_stratixiii 2011:01:19:21:13:40:SJ cbx_stratixv 2011:01:19:21:13:40:SJ cbx_util_mgl 2011:01:19:21:13:40:SJ  VERSION_END


//dffpipe DELAY=2 WIDTH=9 clock clrn d q ALTERA_INTERNAL_OPTIONS=AUTO_SHIFT_REGISTER_RECOGNITION=OFF
//VERSION_BEGIN 10.1SP1 cbx_mgl 2011:01:19:21:15:40:SJ cbx_stratixii 2011:01:19:21:13:40:SJ cbx_util_mgl 2011:01:19:21:13:40:SJ  VERSION_END

//synthesis_resources = reg 18 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"AUTO_SHIFT_REGISTER_RECOGNITION=OFF"} *)
module  fifo8_copy_dffpipe
	( 
	clock,
	clrn,
	d,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   clrn;
	input   [8:0]  d;
	output   [8:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   clock;
	tri1   clrn;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[8:0]	dffe16a;
	reg	[8:0]	dffe17a;
	wire ena;
	wire prn;
	wire sclr;

	// synopsys translate_off
	initial
		dffe16a = 0;
	// synopsys translate_on
	always @ ( posedge clock or  negedge prn or  negedge clrn)
		if (prn == 1'b0) dffe16a <= {9{1'b1}};
		else if (clrn == 1'b0) dffe16a <= 9'b0;
		else if  (ena == 1'b1)   dffe16a <= (d & {9{(~ sclr)}});
	// synopsys translate_off
	initial
		dffe17a = 0;
	// synopsys translate_on
	always @ ( posedge clock or  negedge prn or  negedge clrn)
		if (prn == 1'b0) dffe17a <= {9{1'b1}};
		else if (clrn == 1'b0) dffe17a <= 9'b0;
		else if  (ena == 1'b1)   dffe17a <= (dffe16a & {9{(~ sclr)}});
	assign
		ena = 1'b1,
		prn = 1'b1,
		q = dffe17a,
		sclr = 1'b0;
endmodule //fifo8_copy_dffpipe

//synthesis_resources = reg 18 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"X_ON_VIOLATION_OPTION=OFF;SYNCHRONIZER_IDENTIFICATION=FORCED_IF_ASYNCHRONOUS"} *)
module  fifo8_copy_alt_synch_pipe
	( 
	clock,
	clrn,
	d,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   clrn;
	input   [8:0]  d;
	output   [8:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   clrn;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [8:0]   wire_dffpipe15_q;

	fifo8_copy_dffpipe   dffpipe15
	( 
	.clock(clock),
	.clrn(clrn),
	.d(d),
	.q(wire_dffpipe15_q));
	assign
		q = wire_dffpipe15_q;
endmodule //fifo8_copy_alt_synch_pipe


//dffpipe DELAY=2 WIDTH=9 clock clrn d q ALTERA_INTERNAL_OPTIONS=X_ON_VIOLATION_OPTION=OFF;SYNCHRONIZER_IDENTIFICATION=FORCED_IF_ASYNCHRONOUS
//VERSION_BEGIN 10.1SP1 cbx_a_gray2bin 2011:01:19:21:13:40:SJ cbx_a_graycounter 2011:01:19:21:13:40:SJ cbx_altdpram 2011:01:19:21:13:40:SJ cbx_altsyncram 2011:01:19:21:13:40:SJ cbx_cycloneii 2011:01:19:21:13:40:SJ cbx_dcfifo 2011:01:19:21:13:40:SJ cbx_fifo_common 2011:01:19:21:13:40:SJ cbx_lpm_add_sub 2011:01:19:21:13:40:SJ cbx_lpm_compare 2011:01:19:21:13:40:SJ cbx_lpm_counter 2011:01:19:21:13:40:SJ cbx_lpm_decode 2011:01:19:21:13:40:SJ cbx_lpm_mux 2011:01:19:21:13:40:SJ cbx_mgl 2011:01:19:21:15:40:SJ cbx_scfifo 2011:01:19:21:13:40:SJ cbx_stratix 2011:01:19:21:13:40:SJ cbx_stratixii 2011:01:19:21:13:40:SJ cbx_stratixiii 2011:01:19:21:13:40:SJ cbx_stratixv 2011:01:19:21:13:40:SJ cbx_util_mgl 2011:01:19:21:13:40:SJ  VERSION_END


//dffpipe DELAY=2 WIDTH=9 clock clrn d q ALTERA_INTERNAL_OPTIONS=AUTO_SHIFT_REGISTER_RECOGNITION=OFF
//VERSION_BEGIN 10.1SP1 cbx_mgl 2011:01:19:21:15:40:SJ cbx_stratixii 2011:01:19:21:13:40:SJ cbx_util_mgl 2011:01:19:21:13:40:SJ  VERSION_END

//synthesis_resources = reg 18 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"AUTO_SHIFT_REGISTER_RECOGNITION=OFF"} *)
module  fifo8_copy_dffpipe1
	( 
	clock,
	clrn,
	d,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   clrn;
	input   [8:0]  d;
	output   [8:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   clock;
	tri1   clrn;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[8:0]	dffe19a;
	reg	[8:0]	dffe20a;
	wire ena;
	wire prn;
	wire sclr;

	// synopsys translate_off
	initial
		dffe19a = 0;
	// synopsys translate_on
	always @ ( posedge clock or  negedge prn or  negedge clrn)
		if (prn == 1'b0) dffe19a <= {9{1'b1}};
		else if (clrn == 1'b0) dffe19a <= 9'b0;
		else if  (ena == 1'b1)   dffe19a <= (d & {9{(~ sclr)}});
	// synopsys translate_off
	initial
		dffe20a = 0;
	// synopsys translate_on
	always @ ( posedge clock or  negedge prn or  negedge clrn)
		if (prn == 1'b0) dffe20a <= {9{1'b1}};
		else if (clrn == 1'b0) dffe20a <= 9'b0;
		else if  (ena == 1'b1)   dffe20a <= (dffe19a & {9{(~ sclr)}});
	assign
		ena = 1'b1,
		prn = 1'b1,
		q = dffe20a,
		sclr = 1'b0;
endmodule //fifo8_copy_dffpipe1

//synthesis_resources = reg 18 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"X_ON_VIOLATION_OPTION=OFF;SYNCHRONIZER_IDENTIFICATION=FORCED_IF_ASYNCHRONOUS"} *)
module  fifo8_copy_alt_synch_pipe1
	( 
	clock,
	clrn,
	d,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   clrn;
	input   [8:0]  d;
	output   [8:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   clrn;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [8:0]   wire_dffpipe18_q;

	fifo8_copy_dffpipe1   dffpipe18
	( 
	.clock(clock),
	.clrn(clrn),
	.d(d),
	.q(wire_dffpipe18_q));
	assign
		q = wire_dffpipe18_q;
endmodule //fifo8_copy_alt_synch_pipe1


//lpm_compare DEVICE_FAMILY="Cyclone III" LPM_WIDTH=5 aeb dataa datab
//VERSION_BEGIN 10.1SP1 cbx_cycloneii 2011:01:19:21:13:40:SJ cbx_lpm_add_sub 2011:01:19:21:13:40:SJ cbx_lpm_compare 2011:01:19:21:13:40:SJ cbx_mgl 2011:01:19:21:15:40:SJ cbx_stratix 2011:01:19:21:13:40:SJ cbx_stratixii 2011:01:19:21:13:40:SJ  VERSION_END

//synthesis_resources = 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  fifo8_copy_cmpr
	( 
	aeb,
	dataa,
	datab) /* synthesis synthesis_clearbox=1 */;
	output   aeb;
	input   [4:0]  dataa;
	input   [4:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [4:0]  dataa;
	tri0   [4:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]  aeb_result_wire;
	wire  [0:0]  aneb_result_wire;
	wire  [12:0]  data_wire;
	wire  eq_wire;

	assign
		aeb = eq_wire,
		aeb_result_wire = (~ aneb_result_wire),
		aneb_result_wire = ((data_wire[0] | data_wire[1]) | data_wire[2]),
		data_wire = {datab[4], dataa[4], datab[3], dataa[3], datab[2], dataa[2], datab[1], dataa[1], datab[0], dataa[0], (data_wire[11] ^ data_wire[12]), ((data_wire[7] ^ data_wire[8]) | (data_wire[9] ^ data_wire[10])), ((data_wire[3] ^ data_wire[4]) | (data_wire[5] ^ data_wire[6]))},
		eq_wire = aeb_result_wire;
endmodule //fifo8_copy_cmpr


//lpm_compare DEVICE_FAMILY="Cyclone III" LPM_WIDTH=4 aeb dataa datab
//VERSION_BEGIN 10.1SP1 cbx_cycloneii 2011:01:19:21:13:40:SJ cbx_lpm_add_sub 2011:01:19:21:13:40:SJ cbx_lpm_compare 2011:01:19:21:13:40:SJ cbx_mgl 2011:01:19:21:15:40:SJ cbx_stratix 2011:01:19:21:13:40:SJ cbx_stratixii 2011:01:19:21:13:40:SJ  VERSION_END

//synthesis_resources = 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  fifo8_copy_cmpr1
	( 
	aeb,
	dataa,
	datab) /* synthesis synthesis_clearbox=1 */;
	output   aeb;
	input   [3:0]  dataa;
	input   [3:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [3:0]  dataa;
	tri0   [3:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]  aeb_result_wire;
	wire  [0:0]  aneb_result_wire;
	wire  [9:0]  data_wire;
	wire  eq_wire;

	assign
		aeb = eq_wire,
		aeb_result_wire = (~ aneb_result_wire),
		aneb_result_wire = (data_wire[0] | data_wire[1]),
		data_wire = {datab[3], dataa[3], datab[2], dataa[2], datab[1], dataa[1], datab[0], dataa[0], ((data_wire[6] ^ data_wire[7]) | (data_wire[8] ^ data_wire[9])), ((data_wire[2] ^ data_wire[3]) | (data_wire[4] ^ data_wire[5]))},
		eq_wire = aeb_result_wire;
endmodule //fifo8_copy_cmpr1


//lpm_mux DEVICE_FAMILY="Cyclone III" LPM_SIZE=2 LPM_WIDTH=1 LPM_WIDTHS=1 data result sel
//VERSION_BEGIN 10.1SP1 cbx_lpm_mux 2011:01:19:21:13:40:SJ cbx_mgl 2011:01:19:21:15:40:SJ  VERSION_END

//synthesis_resources = lut 1 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  fifo8_copy_mux
	( 
	data,
	result,
	sel) /* synthesis synthesis_clearbox=1 */;
	input   [1:0]  data;
	output   [0:0]  result;
	input   [0:0]  sel;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [1:0]  data;
	tri0   [0:0]  sel;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]  result_node;
	wire  [0:0]  sel_node;
	wire  [1:0]  w_data455w;

	assign
		result = result_node,
		result_node = {((sel_node & w_data455w[1]) | ((~ sel_node) & w_data455w[0]))},
		sel_node = {sel[0]},
		w_data455w = {data[1:0]};
endmodule //fifo8_copy_mux

//synthesis_resources = lut 4 M9K 1 reg 115 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"AUTO_SHIFT_REGISTER_RECOGNITION=OFF;REMOVE_DUPLICATE_REGISTERS=OFF;SYNCHRONIZER_IDENTIFICATION=OFF;SYNCHRONIZATION_REGISTER_CHAIN_LENGTH = 3;suppress_da_rule_internal=d101;suppress_da_rule_internal=d102;-name CUT ON -from rdptr_g -to ws_dgrp|dffpipe18|dffe19a;-name SDC_STATEMENT \"set_false_path -from *rdptr_g* -to *ws_dgrp|fifo8_copy_dffpipe1:dffpipe18|dffe19a* \";-name CUT ON -from delayed_wrptr_g -to rs_dgwp|dffpipe15|dffe16a;-name SDC_STATEMENT \"set_false_path -from *delayed_wrptr_g* -to *rs_dgwp|fifo8_copy_dffpipe:dffpipe15|dffe16a* \""} *)
module  fifo8_copy_dcfifo
	( 
	aclr,
	data,
	q,
	rdclk,
	rdempty,
	rdreq,
	wrclk,
	wrfull,
	wrreq) /* synthesis synthesis_clearbox=1 */;
	input   aclr;
	input   [7:0]  data;
	output   [7:0]  q;
	input   rdclk;
	output   rdempty;
	input   rdreq;
	input   wrclk;
	output   wrfull;
	input   wrreq;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [8:0]   wire_rdptr_g1p_q;
	wire  [8:0]   wire_wrptr_g1p_q;
	wire  [8:0]   wire_wrptr_gp_q;
	wire  [7:0]   wire_fifo_ram_q_b;
	reg	[8:0]	delayed_wrptr_g;
	(* ALTERA_ATTRIBUTE = {"SYNCHRONIZER_IDENTIFICATION=FORCED_IF_ASYNCHRONOUS;POWER_UP_LEVEL=HIGH"} *)
	reg	rdemp_eq_comp_lsb_aeb;
	(* ALTERA_ATTRIBUTE = {"SYNCHRONIZER_IDENTIFICATION=FORCED_IF_ASYNCHRONOUS;POWER_UP_LEVEL=HIGH"} *)
	reg	rdemp_eq_comp_msb_aeb;
	reg	[8:0]	rdptr_g;
	(* ALTERA_ATTRIBUTE = {"SYNCHRONIZER_IDENTIFICATION=FORCED_IF_ASYNCHRONOUS"} *)
	reg	[8:0]	rs_dgwp_reg;
	(* ALTERA_ATTRIBUTE = {"SYNCHRONIZER_IDENTIFICATION=FORCED_IF_ASYNCHRONOUS"} *)
	reg	wrfull_eq_comp_lsb_mux_reg;
	(* ALTERA_ATTRIBUTE = {"SYNCHRONIZER_IDENTIFICATION=FORCED_IF_ASYNCHRONOUS"} *)
	reg	wrfull_eq_comp_msb_mux_reg;
	(* ALTERA_ATTRIBUTE = {"SYNCHRONIZER_IDENTIFICATION=FORCED_IF_ASYNCHRONOUS"} *)
	reg	[8:0]	ws_dgrp_reg;
	wire  [8:0]   wire_rs_dgwp_q;
	wire  [8:0]   wire_ws_dgrp_q;
	wire  wire_rdempty_eq_comp1_lsb_aeb;
	wire  wire_rdempty_eq_comp1_msb_aeb;
	wire  wire_rdempty_eq_comp_lsb_aeb;
	wire  wire_rdempty_eq_comp_msb_aeb;
	wire  wire_wrfull_eq_comp1_lsb_aeb;
	wire  wire_wrfull_eq_comp1_msb_aeb;
	wire  wire_wrfull_eq_comp_lsb_aeb;
	wire  wire_wrfull_eq_comp_msb_aeb;
	wire  [0:0]   wire_rdemp_eq_comp_lsb_mux_result;
	wire  [0:0]   wire_rdemp_eq_comp_msb_mux_result;
	wire  [0:0]   wire_wrfull_eq_comp_lsb_mux_result;
	wire  [0:0]   wire_wrfull_eq_comp_msb_mux_result;
	wire  int_rdempty;
	wire  int_wrfull;
	wire  [7:0]  ram_address_a;
	wire  [7:0]  ram_address_b;
	wire  valid_rdreq;
	wire  valid_wrreq;
	wire  [8:0]  wrptr_g1s;
	wire  [8:0]  wrptr_gs;

	fifo8_copy_a_graycounter   rdptr_g1p
	( 
	.aclr(aclr),
	.clock(rdclk),
	.cnt_en(valid_rdreq),
	.q(wire_rdptr_g1p_q));
	fifo8_copy_a_graycounter1   wrptr_g1p
	( 
	.aclr(aclr),
	.clock(wrclk),
	.cnt_en(valid_wrreq),
	.q(wire_wrptr_g1p_q));
	fifo8_copy_a_graycounter12   wrptr_gp
	( 
	.aclr(aclr),
	.clock(wrclk),
	.cnt_en(valid_wrreq),
	.q(wire_wrptr_gp_q));
	fifo8_copy_altsyncram   fifo_ram
	( 
	.aclr1(aclr),
	.address_a(ram_address_a),
	.address_b(ram_address_b),
	.addressstall_b((~ valid_rdreq)),
	.clock0(wrclk),
	.clock1(rdclk),
	.clocken1(valid_rdreq),
	.data_a(data),
	.q_b(wire_fifo_ram_q_b),
	.wren_a(valid_wrreq));
	// synopsys translate_off
	initial
		delayed_wrptr_g = 0;
	// synopsys translate_on
	always @ ( posedge wrclk or  posedge aclr)
		if (aclr == 1'b1) delayed_wrptr_g <= 9'b0;
		else  delayed_wrptr_g <= wire_wrptr_gp_q;
	// synopsys translate_off
	initial
		rdemp_eq_comp_lsb_aeb = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge rdclk or  posedge aclr)
		if (aclr == 1'b1) rdemp_eq_comp_lsb_aeb <= {1{1'b1}};
		else  rdemp_eq_comp_lsb_aeb <= wire_rdemp_eq_comp_lsb_mux_result;
	// synopsys translate_off
	initial
		rdemp_eq_comp_msb_aeb = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge rdclk or  posedge aclr)
		if (aclr == 1'b1) rdemp_eq_comp_msb_aeb <= {1{1'b1}};
		else  rdemp_eq_comp_msb_aeb <= wire_rdemp_eq_comp_msb_mux_result;
	// synopsys translate_off
	initial
		rdptr_g = 0;
	// synopsys translate_on
	always @ ( posedge rdclk or  posedge aclr)
		if (aclr == 1'b1) rdptr_g <= 9'b0;
		else if  (valid_rdreq == 1'b1)   rdptr_g <= wire_rdptr_g1p_q;
	// synopsys translate_off
	initial
		rs_dgwp_reg = 0;
	// synopsys translate_on
	always @ ( posedge rdclk or  posedge aclr)
		if (aclr == 1'b1) rs_dgwp_reg <= 9'b0;
		else  rs_dgwp_reg <= wire_rs_dgwp_q;
	// synopsys translate_off
	initial
		wrfull_eq_comp_lsb_mux_reg = 0;
	// synopsys translate_on
	always @ ( posedge wrclk or  posedge aclr)
		if (aclr == 1'b1) wrfull_eq_comp_lsb_mux_reg <= 1'b0;
		else  wrfull_eq_comp_lsb_mux_reg <= wire_wrfull_eq_comp_lsb_mux_result;
	// synopsys translate_off
	initial
		wrfull_eq_comp_msb_mux_reg = 0;
	// synopsys translate_on
	always @ ( posedge wrclk or  posedge aclr)
		if (aclr == 1'b1) wrfull_eq_comp_msb_mux_reg <= 1'b0;
		else  wrfull_eq_comp_msb_mux_reg <= wire_wrfull_eq_comp_msb_mux_result;
	// synopsys translate_off
	initial
		ws_dgrp_reg = 0;
	// synopsys translate_on
	always @ ( posedge wrclk or  posedge aclr)
		if (aclr == 1'b1) ws_dgrp_reg <= 9'b0;
		else  ws_dgrp_reg <= wire_ws_dgrp_q;
	fifo8_copy_alt_synch_pipe   rs_dgwp
	( 
	.clock(rdclk),
	.clrn((~ aclr)),
	.d(delayed_wrptr_g),
	.q(wire_rs_dgwp_q));
	fifo8_copy_alt_synch_pipe1   ws_dgrp
	( 
	.clock(wrclk),
	.clrn((~ aclr)),
	.d(rdptr_g),
	.q(wire_ws_dgrp_q));
	fifo8_copy_cmpr   rdempty_eq_comp1_lsb
	( 
	.aeb(wire_rdempty_eq_comp1_lsb_aeb),
	.dataa(wire_rs_dgwp_q[4:0]),
	.datab(wire_rdptr_g1p_q[4:0]));
	fifo8_copy_cmpr1   rdempty_eq_comp1_msb
	( 
	.aeb(wire_rdempty_eq_comp1_msb_aeb),
	.dataa(wire_rs_dgwp_q[8:5]),
	.datab(wire_rdptr_g1p_q[8:5]));
	fifo8_copy_cmpr   rdempty_eq_comp_lsb
	( 
	.aeb(wire_rdempty_eq_comp_lsb_aeb),
	.dataa(wire_rs_dgwp_q[4:0]),
	.datab(rdptr_g[4:0]));
	fifo8_copy_cmpr1   rdempty_eq_comp_msb
	( 
	.aeb(wire_rdempty_eq_comp_msb_aeb),
	.dataa(wire_rs_dgwp_q[8:5]),
	.datab(rdptr_g[8:5]));
	fifo8_copy_cmpr   wrfull_eq_comp1_lsb
	( 
	.aeb(wire_wrfull_eq_comp1_lsb_aeb),
	.dataa(wire_ws_dgrp_q[4:0]),
	.datab(wrptr_g1s[4:0]));
	fifo8_copy_cmpr1   wrfull_eq_comp1_msb
	( 
	.aeb(wire_wrfull_eq_comp1_msb_aeb),
	.dataa(wire_ws_dgrp_q[8:5]),
	.datab(wrptr_g1s[8:5]));
	fifo8_copy_cmpr   wrfull_eq_comp_lsb
	( 
	.aeb(wire_wrfull_eq_comp_lsb_aeb),
	.dataa(wire_ws_dgrp_q[4:0]),
	.datab(wrptr_gs[4:0]));
	fifo8_copy_cmpr1   wrfull_eq_comp_msb
	( 
	.aeb(wire_wrfull_eq_comp_msb_aeb),
	.dataa(wire_ws_dgrp_q[8:5]),
	.datab(wrptr_gs[8:5]));
	fifo8_copy_mux   rdemp_eq_comp_lsb_mux
	( 
	.data({wire_rdempty_eq_comp1_lsb_aeb, wire_rdempty_eq_comp_lsb_aeb}),
	.result(wire_rdemp_eq_comp_lsb_mux_result),
	.sel(valid_rdreq));
	fifo8_copy_mux   rdemp_eq_comp_msb_mux
	( 
	.data({wire_rdempty_eq_comp1_msb_aeb, wire_rdempty_eq_comp_msb_aeb}),
	.result(wire_rdemp_eq_comp_msb_mux_result),
	.sel(valid_rdreq));
	fifo8_copy_mux   wrfull_eq_comp_lsb_mux
	( 
	.data({wire_wrfull_eq_comp1_lsb_aeb, wire_wrfull_eq_comp_lsb_aeb}),
	.result(wire_wrfull_eq_comp_lsb_mux_result),
	.sel(valid_wrreq));
	fifo8_copy_mux   wrfull_eq_comp_msb_mux
	( 
	.data({wire_wrfull_eq_comp1_msb_aeb, wire_wrfull_eq_comp_msb_aeb}),
	.result(wire_wrfull_eq_comp_msb_mux_result),
	.sel(valid_wrreq));
	assign
		int_rdempty = (rdemp_eq_comp_lsb_aeb & rdemp_eq_comp_msb_aeb),
		int_wrfull = (wrfull_eq_comp_lsb_mux_reg & wrfull_eq_comp_msb_mux_reg),
		q = wire_fifo_ram_q_b,
		ram_address_a = {(wire_wrptr_gp_q[8] ^ wire_wrptr_gp_q[7]), wire_wrptr_gp_q[6:0]},
		ram_address_b = {(wire_rdptr_g1p_q[8] ^ wire_rdptr_g1p_q[7]), wire_rdptr_g1p_q[6:0]},
		rdempty = int_rdempty,
		valid_rdreq = rdreq,
		valid_wrreq = wrreq,
		wrfull = int_wrfull,
		wrptr_g1s = {(~ wire_wrptr_g1p_q[8]), (~ wire_wrptr_g1p_q[7]), wire_wrptr_g1p_q[6:0]},
		wrptr_gs = {(~ wire_wrptr_gp_q[8]), (~ wire_wrptr_gp_q[7]), wire_wrptr_gp_q[6:0]};
endmodule //fifo8_copy_dcfifo
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module fifo8_copy (
	aclr,
	data,
	rdclk,
	rdreq,
	wrclk,
	wrreq,
	q,
	rdempty,
	wrfull)/* synthesis synthesis_clearbox = 1 */;

	input	  aclr;
	input	[7:0]  data;
	input	  rdclk;
	input	  rdreq;
	input	  wrclk;
	input	  wrreq;
	output	[7:0]  q;
	output	  rdempty;
	output	  wrfull;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0	  aclr;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  sub_wire0;
	wire [7:0] sub_wire1;
	wire  sub_wire2;
	wire  wrfull = sub_wire0;
	wire [7:0] q = sub_wire1[7:0];
	wire  rdempty = sub_wire2;

	fifo8_copy_dcfifo	fifo8_copy_dcfifo_component (
				.rdclk (rdclk),
				.wrclk (wrclk),
				.wrreq (wrreq),
				.aclr (aclr),
				.data (data),
				.rdreq (rdreq),
				.wrfull (sub_wire0),
				.q (sub_wire1),
				.rdempty (sub_wire2));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: AlmostEmpty NUMERIC "0"
// Retrieval info: PRIVATE: AlmostEmptyThr NUMERIC "-1"
// Retrieval info: PRIVATE: AlmostFull NUMERIC "0"
// Retrieval info: PRIVATE: AlmostFullThr NUMERIC "-1"
// Retrieval info: PRIVATE: CLOCKS_ARE_SYNCHRONIZED NUMERIC "0"
// Retrieval info: PRIVATE: Clock NUMERIC "4"
// Retrieval info: PRIVATE: Depth NUMERIC "256"
// Retrieval info: PRIVATE: Empty NUMERIC "1"
// Retrieval info: PRIVATE: Full NUMERIC "1"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone III"
// Retrieval info: PRIVATE: LE_BasedFIFO NUMERIC "0"
// Retrieval info: PRIVATE: LegacyRREQ NUMERIC "1"
// Retrieval info: PRIVATE: MAX_DEPTH_BY_9 NUMERIC "0"
// Retrieval info: PRIVATE: OVERFLOW_CHECKING NUMERIC "1"
// Retrieval info: PRIVATE: Optimize NUMERIC "1"
// Retrieval info: PRIVATE: RAM_BLOCK_TYPE NUMERIC "0"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: UNDERFLOW_CHECKING NUMERIC "1"
// Retrieval info: PRIVATE: UsedW NUMERIC "1"
// Retrieval info: PRIVATE: Width NUMERIC "8"
// Retrieval info: PRIVATE: dc_aclr NUMERIC "1"
// Retrieval info: PRIVATE: diff_widths NUMERIC "0"
// Retrieval info: PRIVATE: msb_usedw NUMERIC "0"
// Retrieval info: PRIVATE: output_width NUMERIC "8"
// Retrieval info: PRIVATE: rsEmpty NUMERIC "1"
// Retrieval info: PRIVATE: rsFull NUMERIC "0"
// Retrieval info: PRIVATE: rsUsedW NUMERIC "0"
// Retrieval info: PRIVATE: sc_aclr NUMERIC "0"
// Retrieval info: PRIVATE: sc_sclr NUMERIC "0"
// Retrieval info: PRIVATE: wsEmpty NUMERIC "0"
// Retrieval info: PRIVATE: wsFull NUMERIC "1"
// Retrieval info: PRIVATE: wsUsedW NUMERIC "0"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone III"
// Retrieval info: CONSTANT: LPM_NUMWORDS NUMERIC "256"
// Retrieval info: CONSTANT: LPM_SHOWAHEAD STRING "OFF"
// Retrieval info: CONSTANT: LPM_TYPE STRING "dcfifo"
// Retrieval info: CONSTANT: LPM_WIDTH NUMERIC "8"
// Retrieval info: CONSTANT: LPM_WIDTHU NUMERIC "8"
// Retrieval info: CONSTANT: OVERFLOW_CHECKING STRING "OFF"
// Retrieval info: CONSTANT: RDSYNC_DELAYPIPE NUMERIC "5"
// Retrieval info: CONSTANT: UNDERFLOW_CHECKING STRING "OFF"
// Retrieval info: CONSTANT: USE_EAB STRING "ON"
// Retrieval info: CONSTANT: WRITE_ACLR_SYNCH STRING "OFF"
// Retrieval info: CONSTANT: WRSYNC_DELAYPIPE NUMERIC "5"
// Retrieval info: USED_PORT: aclr 0 0 0 0 INPUT GND "aclr"
// Retrieval info: USED_PORT: data 0 0 8 0 INPUT NODEFVAL "data[7..0]"
// Retrieval info: USED_PORT: q 0 0 8 0 OUTPUT NODEFVAL "q[7..0]"
// Retrieval info: USED_PORT: rdclk 0 0 0 0 INPUT NODEFVAL "rdclk"
// Retrieval info: USED_PORT: rdempty 0 0 0 0 OUTPUT NODEFVAL "rdempty"
// Retrieval info: USED_PORT: rdreq 0 0 0 0 INPUT NODEFVAL "rdreq"
// Retrieval info: USED_PORT: wrclk 0 0 0 0 INPUT NODEFVAL "wrclk"
// Retrieval info: USED_PORT: wrfull 0 0 0 0 OUTPUT NODEFVAL "wrfull"
// Retrieval info: USED_PORT: wrreq 0 0 0 0 INPUT NODEFVAL "wrreq"
// Retrieval info: CONNECT: @aclr 0 0 0 0 aclr 0 0 0 0
// Retrieval info: CONNECT: @data 0 0 8 0 data 0 0 8 0
// Retrieval info: CONNECT: @rdclk 0 0 0 0 rdclk 0 0 0 0
// Retrieval info: CONNECT: @rdreq 0 0 0 0 rdreq 0 0 0 0
// Retrieval info: CONNECT: @wrclk 0 0 0 0 wrclk 0 0 0 0
// Retrieval info: CONNECT: @wrreq 0 0 0 0 wrreq 0 0 0 0
// Retrieval info: CONNECT: q 0 0 8 0 @q 0 0 8 0
// Retrieval info: CONNECT: rdempty 0 0 0 0 @rdempty 0 0 0 0
// Retrieval info: CONNECT: wrfull 0 0 0 0 @wrfull 0 0 0 0
// Retrieval info: GEN_FILE: TYPE_NORMAL fifo8_copy.vhd TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL fifo8_copy.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL fifo8_copy.cmp TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL fifo8_copy.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL fifo8_copy_inst.vhd FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL fifo8_copy_syn.v TRUE
